### PR TITLE
result page added

### PR DESCRIPTION
**Pull request by avindhawale**
- result page added
- home link added
image

### CODE REVIEW

**Review by vinc3nati — APPROVED** [review]
good work

**Review by Hnh013 — APPROVED** [review]
looks good to merge , code is structured and good use of variables !

**Review by Aman-Jain1996 — APPROVED** [review]
Everything looks good but few suggestions :- 

- Check contrast of font color with bg color
- Apply some transition on toggle answer click so that it looks smooth
- Give some margin-bottom to last answer so that it looks detachted from bottom screen

**Review by muskaanshah — APPROVED** [review]
Suggestion: The color difference between the background colour and the correct answer is very less, try to use a different colour to highlight the correct answer or change the background colour to a lighter shade
Otherwise looks good

**Pull request merged**
